### ISSUE TITLE
SecretScanner report does not load

### ISSUE THREAD

**Issue by AnuradhaDas** [boyter/secret-scanner-confluence#2]
I have started SecreScanner trial today after enabling on our sandbox. I cannot see the scan report, it just says " App is not responding. Wait or [cancel](https://mitel-sandbox-189.atlassian.net/wiki/plugins/servlet/ac/boyter-secret-scanner-confluence/secret-scanner-report#)?". Tried on Brave and Firefox browser , no luck !

 

thanks,

Anuradha

**Comment by boyter** [comment]
@AnuradhaDas Would you be comfortable sharing your sandbox name? I don't see any evaluations started in the last day on the Marketplace licences list, but that could be an issue with Atlassian right now. It should match whatever you use to login, so mysandbox.atlassian.net/wiki/ where mysandbox is the bit I want to know.

My guess is that its something like `*****-****box-189`. If you can confirm that it is that one that would help a lot.

It looks like there is a problem coming back from Atlassian for some requests right now. https://status.atlassian.com indicates there are some problems with Atlassian right now, and you may be affected. This issue has been happening for a week or so.

**Comment by boyter** [comment]
@AnuradhaDas Can confirm that I am able to replicate the issue on my own instance. However I have another instance with access and it loads correctly.

This appears to be related to the Atlassian issues that are ongoing right now.

When this becomes resolved, I will be happy to create a code for you to get another month trial, unless Atlassian themselves are able to resolve the issue.

**Comment by boyter** [comment]
Here is an example of another application where one is working, and the other on a different confluence instance is not working or even loading.

![image](https://user-images.githubusercontent.com/612151/162883289-c013463f-c02d-4de1-92aa-2f3256a29ff0.png)

**Comment by AnuradhaDas** [comment]
Hi ,
Our instance name is https://mitel-sandbox-189.atlassian.net/wiki/plugins/servlet/ac/boyter-secret-scanner-confluence/secret-scanner-report.

**Comment by boyter** [comment]
Can 100% confirm you are being affected by the Atlassian issues then @AnuradhaDas 

The moment its resolved we should be able to extend your trial.

**Comment by boyter** [comment]
@AnuradhaDas Now there appears to be some other issue atlassian has not told me about. 

Investigating this now.
