### ISSUE TITLE
Trial extension needed.

### ISSUE THREAD

**Issue by Estebantxo82** [boyter/secret-scanner-confluence#4]
Good afternoon.

I write you to request a trial extension for your app. We are in the process of migrate to the cloud, and we have your plugin installed in our trial cloud instance. We will start migrating our data center instance next week.

We were able to extend the trial licenses for all our other plugins with Atlassian support, but in your case they asked us to contact you and get the permission with this details: “The screenshot would need to contain the email address of the vendor, the name of the app, and the period approved for the extended evaluation or the date the evaluation is approved for the extension.”

Thank you!

**Comment by boyter** [comment]
Hi @Estebantxo82 thats not a problem. Can you email me at ben@boyter.org with your details and I will set that up for you.
